/*

This file does the mixed-effects regressions for the paper.

*/


infile designNumber replication construct minFactorLoading meanFactorLoading maxCrossLoading trueR2 incomingPathsCorrect incomingPathsExtra incomingPathsOmitted outgoingPathsCorrect outgoingPathsExtra outgoingPathsOmitted trueScoreCorrelation deltaR2 numberOfConstructs expectedNumberOfOutgoingPaths populationPathValues omittedPathsShare extraPaths sampleSize indicatorCount factorLoading factorLoadingInterval maxErrorCorrelation methodVariance  using  constructData.data , automatic

xi: xtmixed trueScoreCorrelation minFactorLoading meanFactorLoading maxCrossLoading trueR2 incomingPathsCorrect incomingPathsExtra incomingPathsOmitted outgoingPathsCorrect outgoingPathsExtra outgoingPathsOmitted || designNumber: numberOfConstructs expectedNumberOfOutgoingPaths i.populationPathValues omittedPathsShare extraPaths sampleSize indicatorCount factorLoading factorLoadingInterval maxErrorCorrelation methodVariance 